### ISSUE TITLE
Validation for Project details Start and End dates

### ISSUE THREAD

**Issue by SwapnilSRedekar** [Me-Abhishek-patel/Project_Progress_Tracker#18]
@Me-Abhishek-patel Can we add validation for Project details Start and End date fields in order to avoid End date to be less than Start date. Please suggest

**Comment by Me-Abhishek-patel** [comment]
@SwapnilSRedekar YES, that will be great.

**Comment by SwapnilSRedekar** [comment]
@Me-Abhishek-patel PR raised for above discussed issue https://github.com/Me-Abhishek-patel/Project_Progress_Tracker/pull/19
