### ISSUE TITLE
Any Contribution in app improvement

### ISSUE THREAD

**Issue by Me-Abhishek-patel** [Me-Abhishek-patel/Project_Progress_Tracker#5]
**Help in improving this app by adding missing features.**

- Rename feature (project, activity, activity)
- Copy tasks or activities (withing same project/task OR from one to another)
- According to your imagination

**Contribution **

1. frok repo
2. clone it
3. make changes
4. create a new branch and commit changes
5. push and open pull req.

_dev branch should be forked and pull req should be opened to dev branch only_

**Comment by Procoder16** [comment]
@Me-Abhishek-patel  I would like to contribute to this issue.

Can I do this?

If so, please assign me.

**Comment by Me-Abhishek-patel** [comment]
@Procoder16 Yes, You can do this.

**Comment by Procoder16** [comment]
thank you @Me-Abhishek-patel sir

**Comment by TomerPacific** [comment]
@Me-Abhishek-patel , I'd also like to help. What is @Procoder16  working on? So we don't work on the same issue. Also, is there anything you liked to prioritize?

**Comment by Procoder16** [comment]
@TomerPacific I would like to view the entire app and would like to add a new feature if I find something is missing.

**Comment by Me-Abhishek-patel** [comment]
@TomerPacific @Procoder16 It'll be better if u can raise a issue and then work on it

**Comment by TomerPacific** [comment]
@Me-Abhishek-patel , got it. In this issue you mentioned that you would like the ability to rename a feature. Is this still an issue or have you developed it?

**Comment by Me-Abhishek-patel** [comment]
> n this issue you mentioned that you would like the ability to rename a feature.

@TomerPacific It is still an issue.
You can go ahead if u like

**Comment by Me-Abhishek-patel** [comment]
@TomerPacific for reference -
when clicked on rename it shows a toast "rename Clicked"
replace it with actual ability to rename.
![WhatsApp Image 2020-10-03 at 8 11 22 PM](https://user-images.githubusercontent.com/62820147/94994469-5e0c0e80-05b5-11eb-8c39-ab7cd488a163.jpeg)

**Comment by TomerPacific** [comment]
@Me-Abhishek-patel  - got it. Would you like me to open a separate issue for this?

**Comment by Me-Abhishek-patel** [comment]
> @Me-Abhishek-patel - got it. Would you like me to open a separate issue for this?

No need for that

**Comment by TomerPacific** [comment]
@Me-Abhishek-patel , in my implementation, I am presenting an alert dialog to the user to rename the task/activity/project.
Is this the desired behavior?

![qemu-system-i386_neJi2Ll88q](https://user-images.githubusercontent.com/23402988/95001865-dd5e0a00-05d6-11eb-8f7b-1bd449aafd76.png)

**Comment by Me-Abhishek-patel** [comment]
@TomerPacific yes it is perfect 👍

**Comment by TomerPacific** [comment]
@Me-Abhishek-patel , I have created a [PR](https://github.com/Me-Abhishek-patel/Project_Progress_Tracker/pull/15). Let me know what you think.

**Comment by TomerPacific** [comment]
@Me-Abhishek-patel ,

would you mind adding the hacktoberfest-accepted label to this issue and to the PR?
